version: '3'
services:
  nginx:
    image: nginx
    restart: unless-stopped
    depends_on:
      - app
      - signaling
    volumes:
      - ./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - default

  postgres:
    image: postgres
    restart: unless-stopped
    expose:
      - 5432
    environment: #remove this section in a production environment and set this data through command line
      POSTGRES_USER: user
      POSTGRES_PASSWORD: demo1234
      POSTGRES_DB: connect_db
    healthcheck:
      test: pg_isready -d connect_db -U user
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - default

  app:
    build: ./../docker/app/
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    command: uwsgi --ini wsgi.ini
    expose:
      - 8000
    environment:
      - FLASK_APP=core
    volumes:
      - ./../src/app/:/usr/local/lib/python3.12/site-packages/src/:z
    networks:
      - default

  signaling:
    build: ./../docker/signaling/
    restart: unless-stopped
    command: python -u server.py
    expose:
      - 6000
    volumes:
      - ./../src/signaling/:/usr/local/lib/python3.12/site-packages/src/
    networks:
      - default

volumes:
  postgres:

networks:
  default: